openapi: 3.1.0
info:
  title: UnderStance Backend API
  description: >
    Backend API for the UnderStance web app. See our project page for more information: 
paths:
  /questions:
    get:
      summary: Get all questions/issues
      description: Retrieves all the issues from the database
      parameters:
        dingk
      responses:
        "200":
          description: Successful GET
          content:
            application/json:
              type: array
              minItems: 0
              items:
                type: object
                properties:
                  IssueID:
                    type: integer
                    description: ID of issue object
                  Description:
                    type: string
                    description: Full description of issue
                  Summary:
                    type: string
                    description: Short one line summary of issue
        "400":
          description: Bad request - incorrect parameters passed into query
          content:
            application/json:
              type: object
              properties:
                error:
                  type: string
                  enum: ['Invalid Arguments']
                  description: Error message
        "500":
          description: Server error
          content:
            application/json:
              type: object
              properties:
                error:
                  type: string
                  enum: ['Failed to fetch questions']
                  description: Error message
