name: CI script for backend
permissions:
  checks: write
  pull-requests: write
  contents: write

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: npm i
        working-directory: Backend/

      - name: Begin running tests
        run: ENV=test npm run testcov
        working-directory: ./Backend/

      - name: Publish Backend test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            Backend/coverage/results.xml
          comment_title: "🧪 Backend Unit Test Results"

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: Backend/coverage/lcov.info
