name: CI script for backend
permissions:
  checks: write
  pull-requests: write
  contents: write

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      CI: true
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_PRIVILEGED_CLIENT_ID: ${{ secrets.AUTH0_PRIVILEGED_CLIENT_ID }}
      AUTH0_PRIVILEGED_CLIENT_SECRET: ${{ secrets.AUTH0_PRIVILEGED_CLIENT_SECRET }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: npm i
        working-directory: Backend/

      - name: Begin running tests
        run: ENV=test npm run testcov
        working-directory: ./Backend/

      - name: Publish Backend Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            Backend/coverage/results.xml
          check_name: "🧪 Backend Unit Test Results"

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: Backend/coverage/lcov.info
