name: Deploy to Render

on:
  push:
    branches:
      - thad/JIRA-21-create-github-action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Frontend Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}

      - name: Trigger Render Backend Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update Swaggerhub API spec
        run: |
          curl -X POST "https://api.swaggerhub.com/apis/harjun7517/under-stance_backend_api" -H "Authorization: ${{ secrets.SWAGGERHUB_KEY }}" -H "Content-Type: application/yaml" --data-binary @Backend/openapi.yml
      
      - name: Reset test database
        run: |
          sudo systemctl start postgresql.service
          psql "${{ secrets.DB_CONN_STRING }}" -c 'DROP TABLE "Stance", "Party", "Issue";'
          echo "Database dropped!"
          psql "${{ secrets.DB_CONN_STRING }}" -f Backend/10-db-init.sql
          echo "Init DB complete"
          psql "${{ secrets.DB_CONN_STRING }}" -f Backend/tests/setup/20-pop-db.sql
          echo "Pop DB complete"