name: CI script for Frontend
permissions:
  checks: write
  pull-requests: write
  contents: write

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: npm i
        working-directory: Frontend/


      - name: Begin running tests
        run: ENV=test npm test
        working-directory: ./Frontend/src/utils/tests

      - name: Publish Frontend Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            Frontend/coverage/results.xml
          check_name: "🧪 Frontend Unit Test Results"

      # - name: Upload coverage report to codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: Frontend/coverage/lcov.info
