name: CI script for Frontend
permissions:
  checks: write
  pull-requests: write
  contents: write

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: npm i
        working-directory: Frontend/

      - name: Lint & Fix using Standard
        continue-on-error: true
        run: |
          npx standard --fix --env=jest Frontend/ 
      
      - name: Check for remainding lint errors
        id: lint
        continue-on-error: true
        run: |
          set +e  # disable immediate exit on error
          OUTPUT="$(npx standard --env=jest Frontend/ 2>&1)"
          EXIT_CODE=$?
          echo 'lint_output<<EOF' >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT

      - name : Create comment
        if: steps.lint.outputs.exit_code != '0'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **There is one or more linting errors**
            ```
            ${{ steps.lint.outputs.lint_output }}
            ```
            🌏

      - name: Push changed code if lint fails
        if: steps.lint.outputs.exit_code != '0'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Fixed some lint errors"
          git push
          echo "Exiting workflow due to remaining lint errors"
          exit 1


      - name: Begin running tests
        run: ENV=test npm test
        working-directory: ./Frontend/src/utils/tests

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            Frontend/coverage/results.xml

      # - name: Upload coverage report to codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: Frontend/coverage/lcov.info

      - name: Format code using prettier
        uses: creyD/prettier_action@v4.5
        with:
          prettier_options: --write /home/runner/work/UnderStance/UnderStance/Frontend/**/*.{js,jsx,ts,tsx}
          file_pattern: "*.js"
